services:
  cms:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/database.sqlite:/app/backend/database.sqlite
      - ./public:/app/public
    restart: unless-stopped
